version: '3.9'
services:
  api:
    container_name: backend
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: npm run start:dev
